### PR TITLE
[enhance] Replace commons-io with direct java 8 code - Fixes #3

### LINKED ISSUE #3: Replace commons-io with direct usage of Files in jdk8
commons-io is only being used for test purposes to read in file content.  This can be done natively in java 8 just as easily.

### PR DESCRIPTION
**Pull request by hazendaz**
Fixes #3

### CODE REVIEW

**Comment by hazendaz** [comment]
Personally I've never been a fan of static imports but that does make sense over that progression.  I'm good with this since it's just one test class.  I dont have write access here so have at it or adjust it if you like.  Either way I'm good :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ctubbsii** [comment]
@hazendaz I merged it for you. I thought you had write access already. I fixed it, though. You should have it now, for next time.

**Comment by ctubbsii** [comment]
FWIW, I like the review step, even with write access. It's helpful to get consensus, and to get a second opinion, in case there's an error somewhere. :smiley_cat:

**Comment by hazendaz** [comment]
Agreed! Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
